module.exports = {
	version: '0.2',
	language: 'en',

    words: [
        'eleventy',
        '11ty',
        'kairos',
        'mavica',
        'Chronos',
        'Kairos',
        'gcode',
        'Adafruit',
        'autoplay',
        'qwiic',
        'oled',
        'SAMD',
        'backronym',
        'hardpoint',
        'hardpoints',
        'PLA',
        'PETG',
        'powerbank',
        'microcontroller',
        'microcontrollers',
        'gitea',
        'tailscale',
        'userspace',
        'homelab',
    ],
    flagWords: [],

}